// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnkjndmkqsynblndaqzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhua2puZG1rcXN5bmJsbmRhcXp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMTg3NDgsImV4cCI6MjA2NjU5NDc0OH0.joLAOA3STW9yLoRc93gwWI7QIhXS2WQIVtufLX5N6rg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);